[build]
  command = "npm run build"
  publish = "dist/public"

[build.environment]
  NODE_ENV = "production"

[[functions]]
  name = "server"
  runtime = "nodejs18.x"

[dev]
  command = "npm run dev"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200